### ISSUE TITLE
Why image size doesn't match the depth size?

### ISSUE THREAD

**Issue by julianraheema** [heuristicus/spot_ros#103]
I don't know if it is proper to post this ticket here?

Lets say: I have the back camera /spot/camera/back/image and depth /spot/depth/back/image and the camera info's for both camera and depth respectively. I also have /tf topics and /spot/odometery topics. I have been struggling to use rtabmap_ros for the back camera.

camera: rear fisheye camera
image: /spot/camera/back/image ---> 640x480 enconding mono8
depth: /spot/depth/back/image ---> 424x240 encoding 16UC1
camra_info: /spot/camera/back/image_info
depth_camera_info: /spot/depth/back/image_info

How I can use rtabmap using the fisheye camera and the depth? The goal is to have a 2d or 3d map of a room.

I would appreciate your help and comments. 

Thank you.

**Comment by heuristicus** [comment]
We're getting camera information in these lines:

https://github.com/heuristicus/spot_ros/blob/bb82c29e9d51d12d57d53c8b4d4faecb600a1bc8/spot_driver/src/spot_driver/ros_helpers.py#L131-L147

So, what you're seeing is the data we're receiving directly from the spot SDK.

**Comment by julianraheema** [comment]
Thank you.
