### ISSUE TITLE
Spot Depth Image Holes (Bands of Empty Space)

### ISSUE THREAD

**Issue by TankyFranky** [heuristicus/spot_ros#111]
Hello,

I've noticed that the depth images returned by Spot demonstrate holes in the measurement which appear to be a repeating intervals along the ground. I've included an example from RVIZ below. In this example I have converted each of the depth images into a point cloud using the `depth_image_proc` package. 

![realsense_banding](https://user-images.githubusercontent.com/43577151/224137153-7160248b-0e8b-44bb-b0f8-0917e04bd6b9.png)

I am trying to determine the cause of these dead zones in the depth image. From my understanding it could be the reflectivity of the surface (polished vinyl floor) that I am working with, but the dead zone banding effect is also present on black rubber mat surfaces that I have also been testing on.

I have run some tests and noted that when an obstacle is measure (say a cardboard box), the banding effect is minimized when the object is perpendicular to the floor (box standing up straight). It appears objects parallel to the ground suffer from the banding effect.

I am wondering if there is a way to remedy this at the sensor level, I have already tried a camera recalibration. The next question is if other can recomend any filtering steps to help reduce the holes in the depth images.

Thanks.

**Comment by heuristicus** [comment]
This is a question for BD support or the camera manufacturer rather than for us here, I think. We're simply passing through the data that is given to us by the SDK. If information from those sources indicates that we're doing something wrong in the driver I'm happy to reopen.
