### ISSUE TITLE
Error when starting the driver on ROS Melodic on Ubuntu 18.04.5 LTS on a SpotCORE

### ISSUE THREAD

**Issue by Vugul** [heuristicus/spot_ros#117]
Hello, I'm using a Spot Core to get the Spot_ROS driver running to control the Spot. The Core is directly connected to the Spot. My standard Python Version is Python 2.7.17. 
When I'm trying to launch the driver I get the Error messages in the pictures down below. I already tried the "Building for Melodic" chapter but it did not help. 

It would be really awesome if somebody could help me solve the problem.
Thank you so much in advance.

Kind regards,
Vugul

![RoslaunchError1](https://user-images.githubusercontent.com/129513316/229113774-39a9e8f0-8b40-4645-9cf8-4ce99ab4b298.png)
![RoslaunchError2](https://user-images.githubusercontent.com/129513316/229113795-e3be2eca-2441-4eea-ab99-5ff979c3d774.png)

**Comment by heuristicus** [comment]
You should also have a look at https://github.com/heuristicus/spot_ros/issues/101 where I make some suggestions for changes to the driver which should allow it to function on melodic.

**Comment by Vugul** [comment]
Thank you for your help. I will try those steps and see if it works.

Is it possible to just use a virtual environment with python3 and install the Spot Ros Package with Python3 running?
When I try to test the view_model.launch in a Python3 Virtual Environment I get an error that the joint_state_publisher has died and the joints arent visualized in RVIZ.
If it would be possible to install it on a Python3 Environment, I could maybe try to avoid the other problem.

![SpotROS_on_Python3_Venv](https://user-images.githubusercontent.com/129513316/229122467-acc3df7a-a312-473e-b5dd-0a4e65c6ee99.png)
![RVIZ_Python3](https://user-images.githubusercontent.com/129513316/229122679-bb585c4f-ab01-4498-a7c1-419492aa4d18.png)

**Comment by heuristicus** [comment]
Your best bet is probably to install the driver and everything it requires in a docker container on ubuntu 20.04 and noetic, because the crash you are experiencing in the first error you posted is (I believe) due to some changes in the ros packages between melodic and noetic.

It looks like what you've posted isn't running in a python3 environment - you can see in the error that it's using files in python2.7 dist packages.

**Comment by Vugul** [comment]
Would it be possible to delete ROS melodic fully from the SpotCore and install it with a python3 Virtual Environment running to make it only use Python3 and because of this the error from above won´t happen?

**Comment by heuristicus** [comment]
I'm not sure how the spot CORE is configured - based on the BD documentation it seems like it's 18.04 only and there's likely some specific configuration associated with that. As I said above, you're probably best off running noetic in a docker container.
