### ISSUE TITLE
Blender File

### ISSUE THREAD

**Issue by mizeller** [heuristicus/spot_ros#118]
Your model of spot is very nice - I'd like to use it for simulations with Blender. Could you share the blender file of spot (or the textures you used) please?

**Comment by heuristicus** [comment]
You can find the meshes in https://github.com/heuristicus/spot_ros/tree/master/spot_description/meshes, and the urdf which defines how they are put together in https://github.com/heuristicus/spot_ros/tree/master/spot_description/urdf.

**Comment by mizeller** [comment]
Hey! Thanks for your fast reply

I used these files to assemble Spot in Blender. Maybe I'm missing something, but I couldn't figure out how to add the yellow textures to the model as well.

**Comment by heuristicus** [comment]
That's not something we can support here, you'll have to work it out based on the files we have.
