### ISSUE TITLE
Upgrading spot API to v2.1.0

### ISSUE THREAD

**Issue by mqcmd196** [heuristicus/spot_ros#12]
Hi, I have a question.
Does this package compatible with BostonDynamics's new API version 2.1.0?

**Comment by dniewinski** [comment]
It should be compatible with 2.1.0.  I will test today to make sure

**Comment by mqcmd196** [comment]
@dniewinski Thanks a lot!

**Comment by dniewinski** [comment]
Very minor fix pushed.  Works on our spot for 2.1.0
