### ISSUE TITLE
Is anyone else encountering issues with gmapping?

### ISSUE THREAD

**Issue by danchoy** [heuristicus/spot_ros#133]
In my case, I've been using the BD API to collect lidar pointcloud data. Afterward, I employ the pointcloud_to_laser to transform it into laser data. My objective is to use this laser data to create a map with mapping. 
However, I've noticed that despite setting the parent to the body, the vision frame doesn't follow the robot. Has anyone else had this experience?

![vision in the body](https://github.com/heuristicus/spot_ros/assets/34352426/77ebd485-11c9-4205-b343-61b650c3591b)

![vision didn't move with robot](https://github.com/heuristicus/spot_ros/assets/34352426/b4643ec5-a674-42e6-a1c1-8c4d3247b83b)

![vision frame](https://github.com/heuristicus/spot_ros/assets/34352426/dd3abe11-bafd-4ee2-9149-e76ea2eb4cea)

**Comment by heuristicus** [comment]
Closing as out of scope unless the frame output is actually wrong. The vision frame is provided by passing through the transform tree from the robot.
