### ISSUE TITLE
Duplicated publish_depth_images_callback method

### ISSUE THREAD

**Issue by trangml-mit** [heuristicus/spot_ros#147]
There are two methods named publish_depth_images_callback, which is causing the depth only camera image to not be published, even when setting depth_in_visual to False.

https://github.com/heuristicus/spot_ros/blob/2a1d26da976a6376b21b5af9ce5328899fb7a8c4/spot_driver/src/spot_driver/spot_ros.py#L326

and 

https://github.com/heuristicus/spot_ros/blob/2a1d26da976a6376b21b5af9ce5328899fb7a8c4/spot_driver/src/spot_driver/spot_ros.py#L404

One of them could just be renamed.

**Comment by heuristicus** [comment]
Fixed in [6c4ce99](https://github.com/heuristicus/spot_ros/commit/6c4ce991d50f18ebcb909a7295bae918d21d9e16).
