### ISSUE TITLE
ROS API for trajectory cmd

### ISSUE THREAD

**Issue by sktometometo** [heuristicus/spot_ros#15]
[My PR about trajectory cmd](https://github.com/clearpathrobotics/spot_ros/pull/13) uses ROS service as a API for trajectory command which enables spot to move to a given position.
But I think there are 3 candidates of API for trajectory cmd.
- topic ( e.g. /cmd_vel )
- service ( e.g. services in spot_driver such as /spot/stand )
- action ( e.g. [Action API of move_base](http://wiki.ros.org/move_base#Action_API) )

According to [patterns](http://wiki.ros.org/ROS/Patterns/Communication) for ROS Communication API, I implemented trajectory cmd as a service because I thought it is a kind of remote procedure which issue a [robot command](https://dev.bostondynamics.com/docs/concepts/robot_services#robot-command) with Boston Dynamics API.
But it is also good to make trajectory cmd as a topic or an action if treating trajectory cmd as a 'continuous data stream' like /cmd_vel or a 'discrete behavior' like move_base.

**Comment by dniewinski** [comment]
We should keep discussion on the PR so it's all in one place
