### ISSUE TITLE
[Documentation] Deprecated Reference to Application Token

### ISSUE THREAD

**Issue by bd-bbeddard** [heuristicus/spot_ros#3]
As of Spot v2.0.1, Spot no longer requires an application token. We now utilize a license that is local to Spot.

Would you be able to adjust the documentation accordingly? http://www.clearpathrobotics.com/assets/guides/melodic/spot-ros/ros_usage.html#get-an-applicaiton-token

Thanks!

**Comment by dniewinski** [comment]
Just FYI, the source for these docs is here: https://github.com/clearpath-docs/spot-ros-sphinx-tutorials

I haven't had a chance to test the latest version with the ROS driver, but once I get a chance, I will make this change and any fixes in the driver

**Comment by bd-bbeddard** [comment]
Thank you! Sorry for the wrong repo.

**Comment by dniewinski** [comment]
All fixed up.  Minor change to the driver too
