### ISSUE TITLE
Tutorial documentation in this repository

### ISSUE THREAD

**Issue by heuristicus** [heuristicus/spot_ros#35]
The tutorial that is at http://www.clearpathrobotics.com/assets/guides/melodic/spot-ros/ is very useful for anyone starting off with the package. However, it's not in this repository so if we make changes or add new features we can't edit the tutorial/documentation so that people know it exists.

Would it be possible to add that documentation into this repository somehow?

**Comment by dniewinski** [comment]
@heuristicus The API docs are automatically generated from the code, but usage docs are manually created.  Feel free to make changes and submit a PR to the docs here: https://github.com/clearpath-docs/spot-ros-sphinx-tutorials
