### ISSUE TITLE
Apply a standard formatting scheme to python code

### ISSUE THREAD

**Issue by heuristicus** [heuristicus/spot_ros#56]
I thought I'd start a discussion about applying some sort of standard formatting scheme to the python code. I personally find it useful to not have to worry about formatting my code, and just apply a formatter to do it for me. It might be useful to have here as well to make sure all the code has a consistent scheme.

I have recently been using [black](https://black.readthedocs.io/en/stable/index.html), which I find quite pleasant as there are very few options to fiddle with.

**Comment by civerachb-cpr** [comment]
We generally try to follow ROS's guidelines for Python linting: http://wiki.ros.org/roslint
