### ISSUE TITLE
spot trembling gait

### ISSUE THREAD

**Issue by edomil90** [heuristicus/spot_ros#60]
Hi,

I am running spot_ros on a jetson nano that is connected via ethernet to the GXP of our Spot. Everything works fine, but when I try to teleoperate spot, either using the interactive marker on rviz, the teleop_twist_keyboard or just publishing on a topic with the command line, spot moves really bad, kind of trembling. On the contrary, when I use the wasd example of the SDK with the same setup, the gate is smooth as it should be. What can be the problem? Maybe the jetson nano is too slow at sending the commands via spot_ros? thanks for helping!

**Comment by civerachb-cpr** [comment]
What network devices do you have connected to the Jetson? We've noticed in the past that high-bandwidth devices, like a VLP-16, can effectively choke the network connection, causing high latency and this sort of interrupted velocity control.

**Comment by edomil90** [comment]
The Nano does not have other devices connected. We replaced the Nano with Jetson AGX and it goes much better, even though some times Spot still makes some weird steps.

**Comment by Prassi07** [comment]
I think I had this issue too. One thing that helped me resolve this is by increasing the timeout of the velocity_cmd function in spot_wrapper from 0.125 to 0.5. That instantly fixed this. I do not know why this was happening

**Comment by heuristicus** [comment]
Perhaps this is something to do with the rate of whatever you are using to publish messages to the cmd_vel topic. If the rate is slower than the velocity_cmd timeout you will probably observe jerkiness in the motion as the robot starts to move into the stable position and then starts moving agian.

**Comment by edomil90** [comment]
> I think I had this issue too. One thing that helped me resolve this is by increasing the timeout of the velocity_cmd function in spot_wrapper from 0.125 to 0.5. That instantly fixed this. I do not know why this was happening

Thanks for the tip! This solved the issue, I actually noticed that in the wasd example of spot-sdk the timeout is set to 0.6, so this makes sense
