### ISSUE TITLE
protobuf requires Python '>=3.7' but the running Python is 3.6.9 

### ISSUE THREAD

**Issue by 1027743011** [heuristicus/spot_ros#81]
Hi,
First of all thank you for providing this driver.
I am having a  issue that when i use the command  
`pip3 install bosdyn-client bosdyn-mission bosdyn-api bosdyn-core`
it will occur an error that  "protobuf requires Python '>=3.7' but the running Python is 3.6.9" .
So do you have some suggestion to handle this issue ? Thank you again,i have thought many ways to solve this problem ,but id
did not works .

**Comment by heuristicus** [comment]
You should check that the version of python that is installed on your system is above 3.7. The default python version on ubuntu 20.04 should be 3.8.10, based on what I have on my machine.

You can check the version with

```
python3 --version
```

Perhaps you could try

```
sudo apt install python3.8
```

This isn't really the place to ask about upgrading python though.

**Comment by danchoy** [comment]
One potential solution to this issue could be the use of a virtual environment.

https://dev.bostondynamics.com/docs/python/quickstart#manage-multiple-python-environments-with-virtualenv

sudo apt install python pip
sudo apt install python3 pip
python3 -m pip install virtualenv
python3 -m virtualenv --python=/usr/bin/python3 my_spot_env
source my_spot_env/bin/activate
python3 -m pip install --upgrade bosdyn-client bosdyn-mission bosdyn-choreography-client
python3 -m pip install bosdyn-client==3.2.2.post1 bosdyn-mission==3.2.2.post1 bosdyn-choreography-client==3.2.2.post1
python3 -m pip install empy
python3 -m pip install pyyaml
python3 -m pip install rospkg
python3 -m pip install PySide2
sudo apt install python3-empy
