### ISSUE TITLE
RLException: unable to launch

### ISSUE THREAD

**Issue by ruslan98m** [heuristicus/spot_ros#82]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b3f1c0be-1950-11ed-b0f8-646c80dc09a1
process[rosout-1]: started with pid [23669]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [23676]
process[twist_marker_server-3]: started with pid [23677]
process[bluetooth_teleop/joy_node-4]: started with pid [23684]
process[bluetooth_teleop/teleop_twist_joy-5]: started with pid [23691]
**RLException: unable to launch [/workspace/src/spot_ros/spot_driver/scripts/spot_ros joint_states:=/joint_states tf:=/tf __name:=spot_ros __log:=/root/.ros/log/b3f1c0be-1950-11ed-b0f8-646c80dc09a1/spot-spot_ros-6.log]: Permission denied                                   
The traceback for the exception was written to the log file**
[spot/spot_ros-6] killing on exit

**Comment by heuristicus** [comment]
I assume you're using `roslaunch spot_driver driver.launch` to start this. I haven't seen this error and it seems more like an error in your filesystem. Check that the permissions on the script look something like

```
roscd spot_driver
ls -lah spot_ros
-rwxrwxr-x 1 michal michal  125 May 12  2021 spot_ros
```

You may have somehow changed the execution permissions or cloned the repository while being the root user.
